// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (name, email, password)
VALUES ($1, $2, $3)
RETURNING id, name, email, password, created_at, updated_at, avatar_id
`

type CreateAdminParams struct {
	Name     string
	Email    string
	Password string
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRow(ctx, createAdmin, arg.Name, arg.Email, arg.Password)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarID,
	)
	return i, err
}

const findAdminByEmail = `-- name: FindAdminByEmail :one
SELECT id, name, email, password, created_at, updated_at, avatar_id
FROM admins
WHERE email = $1
LIMIT 1
`

func (q *Queries) FindAdminByEmail(ctx context.Context, email string) (Admin, error) {
	row := q.db.QueryRow(ctx, findAdminByEmail, email)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarID,
	)
	return i, err
}

const patchAdminMetadata = `-- name: PatchAdminMetadata :one
UPDATE admins
SET avatar_id = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, email, password, created_at, updated_at, avatar_id
`

type PatchAdminMetadataParams struct {
	ID       pgtype.UUID
	AvatarID pgtype.UUID
}

func (q *Queries) PatchAdminMetadata(ctx context.Context, arg PatchAdminMetadataParams) (Admin, error) {
	row := q.db.QueryRow(ctx, patchAdminMetadata, arg.ID, arg.AvatarID)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarID,
	)
	return i, err
}
