// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: arena.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSpaceElement = `-- name: DeleteSpaceElement :exec
DELETE FROM space_elements WHERE space_id = $1 AND x = $2 AND y = $3
`

type DeleteSpaceElementParams struct {
	SpaceID pgtype.UUID
	X       int32
	Y       int32
}

func (q *Queries) DeleteSpaceElement(ctx context.Context, arg DeleteSpaceElementParams) error {
	_, err := q.db.Exec(ctx, deleteSpaceElement, arg.SpaceID, arg.X, arg.Y)
	return err
}

const getSpaceByID = `-- name: GetSpaceByID :one
SELECT id, width, height FROM spaces WHERE id = $1
`

type GetSpaceByIDRow struct {
	ID     pgtype.UUID
	Width  int32
	Height int32
}

func (q *Queries) GetSpaceByID(ctx context.Context, id pgtype.UUID) (GetSpaceByIDRow, error) {
	row := q.db.QueryRow(ctx, getSpaceByID, id)
	var i GetSpaceByIDRow
	err := row.Scan(&i.ID, &i.Width, &i.Height)
	return i, err
}

const getSpaceElements = `-- name: GetSpaceElements :many
SELECT
    se.x,
    se.y,
    e.id       AS element_id,
    e.image_url,
    e.width    AS element_width,
    e.height   AS element_height,
    e.static
FROM space_elements se
JOIN elements e ON se.element_id = e.id
WHERE se.space_id = $1
`

type GetSpaceElementsRow struct {
	X             int32
	Y             int32
	ElementID     pgtype.UUID
	ImageUrl      string
	ElementWidth  int32
	ElementHeight int32
	Static        bool
}

func (q *Queries) GetSpaceElements(ctx context.Context, spaceID pgtype.UUID) ([]GetSpaceElementsRow, error) {
	rows, err := q.db.Query(ctx, getSpaceElements, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpaceElementsRow
	for rows.Next() {
		var i GetSpaceElementsRow
		if err := rows.Scan(
			&i.X,
			&i.Y,
			&i.ElementID,
			&i.ImageUrl,
			&i.ElementWidth,
			&i.ElementHeight,
			&i.Static,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
