// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: map_creator.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createElement = `-- name: CreateElement :one
INSERT INTO elements (image_url, width, height, static)
VALUES ($1, $2, $3, $4)
RETURNING id, width, height, image_url, static, created_at, updated_at
`

type CreateElementParams struct {
	ImageUrl string
	Width    int32
	Height   int32
	Static   bool
}

func (q *Queries) CreateElement(ctx context.Context, arg CreateElementParams) (Element, error) {
	row := q.db.QueryRow(ctx, createElement,
		arg.ImageUrl,
		arg.Width,
		arg.Height,
		arg.Static,
	)
	var i Element
	err := row.Scan(
		&i.ID,
		&i.Width,
		&i.Height,
		&i.ImageUrl,
		&i.Static,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateElementImage = `-- name: UpdateElementImage :one
UPDATE elements SET image_url = $1, updated_at = NOW()
WHERE id = $2
RETURNING id, width, height, image_url, static, created_at, updated_at
`

type UpdateElementImageParams struct {
	ImageUrl string
	ID       pgtype.UUID
}

func (q *Queries) UpdateElementImage(ctx context.Context, arg UpdateElementImageParams) (Element, error) {
	row := q.db.QueryRow(ctx, updateElementImage, arg.ImageUrl, arg.ID)
	var i Element
	err := row.Scan(
		&i.ID,
		&i.Width,
		&i.Height,
		&i.ImageUrl,
		&i.Static,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
