// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metadata.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findAvatarByID = `-- name: FindAvatarByID :one
SELECT id, image_url, name, created_at, updated_at
FROM avatars
WHERE id = $1
LIMIT 1
`

func (q *Queries) FindAvatarByID(ctx context.Context, id pgtype.UUID) (Avatar, error) {
	row := q.db.QueryRow(ctx, findAvatarByID, id)
	var i Avatar
	err := row.Scan(
		&i.ID,
		&i.ImageUrl,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAvatars = `-- name: GetAvatars :many
SELECT id, image_url, name, created_at, updated_at
FROM avatars
`

func (q *Queries) GetAvatars(ctx context.Context) ([]Avatar, error) {
	rows, err := q.db.Query(ctx, getAvatars)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Avatar
	for rows.Next() {
		var i Avatar
		if err := rows.Scan(
			&i.ID,
			&i.ImageUrl,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
