// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: space.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSpace = `-- name: CreateSpace :one
INSERT INTO spaces (name, width, height, thumbnail)
VALUES ($1, $2, $3, $4)
RETURNING id, name, width, height, thumbnail, created_at, updated_at
`

type CreateSpaceParams struct {
	Name      string
	Width     int32
	Height    int32
	Thumbnail pgtype.Text
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error) {
	row := q.db.QueryRow(ctx, createSpace,
		arg.Name,
		arg.Width,
		arg.Height,
		arg.Thumbnail,
	)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Width,
		&i.Height,
		&i.Thumbnail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
