// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	ID        pgtype.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	AvatarID  pgtype.UUID
}

type Avatar struct {
	ID        pgtype.UUID
	ImageUrl  string
	Name      pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Element struct {
	ID        pgtype.UUID
	Width     int32
	Height    int32
	ImageUrl  string
	Static    bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Map struct {
	ID        pgtype.UUID
	Name      string
	Width     int32
	Height    int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type MapElement struct {
	MapID     pgtype.UUID
	ElementID pgtype.UUID
	X         int32
	Y         int32
}

type Space struct {
	ID        pgtype.UUID
	CreatorID pgtype.UUID
	Name      string
	Width     int32
	Height    int32
	Thumbnail pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type SpaceElement struct {
	SpaceID   pgtype.UUID
	ElementID pgtype.UUID
	X         int32
	Y         int32
}

type User struct {
	ID        pgtype.UUID
	Name      string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	AvatarID  pgtype.UUID
}
